// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/messenger/messenger.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	protocol "github.com/theobitoproject/kankuro/pkg/protocol"
)

// MockMessenger is a mock of Messenger interface.
type MockMessenger struct {
	ctrl     *gomock.Controller
	recorder *MockMessengerMockRecorder
}

// MockMessengerMockRecorder is the mock recorder for MockMessenger.
type MockMessengerMockRecorder struct {
	mock *MockMessenger
}

// NewMockMessenger creates a new mock instance.
func NewMockMessenger(ctrl *gomock.Controller) *MockMessenger {
	mock := &MockMessenger{ctrl: ctrl}
	mock.recorder = &MockMessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessenger) EXPECT() *MockMessengerMockRecorder {
	return m.recorder
}

// WriteLog mocks base method.
func (m *MockMessenger) WriteLog(logLevel protocol.LogLevel, logMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteLog", logLevel, logMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteLog indicates an expected call of WriteLog.
func (mr *MockMessengerMockRecorder) WriteLog(logLevel, logMessage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteLog", reflect.TypeOf((*MockMessenger)(nil).WriteLog), logLevel, logMessage)
}

// WriteState mocks base method.
func (m *MockMessenger) WriteState(stateData *protocol.StateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteState", stateData)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteState indicates an expected call of WriteState.
func (mr *MockMessengerMockRecorder) WriteState(stateData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteState", reflect.TypeOf((*MockMessenger)(nil).WriteState), stateData)
}
