// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/messenger/message_writer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	protocol "github.com/theobitoproject/kankuro/pkg/protocol"
)

// MockMessageWriter is a mock of MessageWriter interface.
type MockMessageWriter struct {
	ctrl     *gomock.Controller
	recorder *MockMessageWriterMockRecorder
}

// MockMessageWriterMockRecorder is the mock recorder for MockMessageWriter.
type MockMessageWriterMockRecorder struct {
	mock *MockMessageWriter
}

// NewMockMessageWriter creates a new mock instance.
func NewMockMessageWriter(ctrl *gomock.Controller) *MockMessageWriter {
	mock := &MockMessageWriter{ctrl: ctrl}
	mock.recorder = &MockMessageWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageWriter) EXPECT() *MockMessageWriterMockRecorder {
	return m.recorder
}

// WriteLog mocks base method.
func (m *MockMessageWriter) WriteLog(logLevel protocol.LogLevel, logMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteLog", logLevel, logMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteLog indicates an expected call of WriteLog.
func (mr *MockMessageWriterMockRecorder) WriteLog(logLevel, logMessage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteLog", reflect.TypeOf((*MockMessageWriter)(nil).WriteLog), logLevel, logMessage)
}

// WriteState mocks base method.
func (m *MockMessageWriter) WriteState(stateData *protocol.StateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteState", stateData)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteState indicates an expected call of WriteState.
func (mr *MockMessageWriterMockRecorder) WriteState(stateData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteState", reflect.TypeOf((*MockMessageWriter)(nil).WriteState), stateData)
}
