// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/messenger/private_messenger.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	protocol "github.com/theobitoproject/kankuro/pkg/protocol"
)

// MockPrivateMessenger is a mock of PrivateMessenger interface.
type MockPrivateMessenger struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessengerMockRecorder
}

// MockPrivateMessengerMockRecorder is the mock recorder for MockPrivateMessenger.
type MockPrivateMessengerMockRecorder struct {
	mock *MockPrivateMessenger
}

// NewMockPrivateMessenger creates a new mock instance.
func NewMockPrivateMessenger(ctrl *gomock.Controller) *MockPrivateMessenger {
	mock := &MockPrivateMessenger{ctrl: ctrl}
	mock.recorder = &MockPrivateMessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessenger) EXPECT() *MockPrivateMessengerMockRecorder {
	return m.recorder
}

// WriteCatalog mocks base method.
func (m *MockPrivateMessenger) WriteCatalog(catalog *protocol.Catalog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteCatalog", catalog)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteCatalog indicates an expected call of WriteCatalog.
func (mr *MockPrivateMessengerMockRecorder) WriteCatalog(catalog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteCatalog", reflect.TypeOf((*MockPrivateMessenger)(nil).WriteCatalog), catalog)
}

// WriteConnectionStat mocks base method.
func (m *MockPrivateMessenger) WriteConnectionStat(status protocol.CheckStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteConnectionStat", status)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteConnectionStat indicates an expected call of WriteConnectionStat.
func (mr *MockPrivateMessengerMockRecorder) WriteConnectionStat(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteConnectionStat", reflect.TypeOf((*MockPrivateMessenger)(nil).WriteConnectionStat), status)
}

// WriteRecord mocks base method.
func (m *MockPrivateMessenger) WriteRecord(record *protocol.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteRecord", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteRecord indicates an expected call of WriteRecord.
func (mr *MockPrivateMessengerMockRecorder) WriteRecord(record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteRecord", reflect.TypeOf((*MockPrivateMessenger)(nil).WriteRecord), record)
}

// WriteSpec mocks base method.
func (m *MockPrivateMessenger) WriteSpec(connectorSpecification *protocol.ConnectorSpecification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteSpec", connectorSpecification)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteSpec indicates an expected call of WriteSpec.
func (mr *MockPrivateMessengerMockRecorder) WriteSpec(connectorSpecification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteSpec", reflect.TypeOf((*MockPrivateMessenger)(nil).WriteSpec), connectorSpecification)
}
